export const participants = [
  { name: '佐藤 匠', instrument: 'drum' },
  { name: '田中 恒一', instrument: 'drum' },
  { name: '森 悠太', instrument: 'drum' },
  { name: '藤田 直樹', instrument: 'drum' },
  { name: '西田 亮', instrument: 'drum' },
  { name: '新井 大地', instrument: 'bass' },
  { name: '近藤 陽翔', instrument: 'bass' },
  { name: '石井 健太', instrument: 'bass' },
  { name: '上田 蒼真', instrument: 'bass' },
  { name: '岡田 蓮', instrument: 'bass' },
  { name: '山本 俊', instrument: 'piano' },
  { name: '原 翼', instrument: 'piano' },
  { name: '酒井 優希', instrument: 'piano' },
  { name: '三浦 隼人', instrument: 'piano' },
  { name: '久米 聡', instrument: 'piano' },
  { name: '松田 玲', instrument: 'piano' },
  { name: '木村 葵', instrument: 'front' },
  { name: '鈴木 陽向', instrument: 'front' },
  { name: '小林 湊', instrument: 'front' },
  { name: '井上 恒一', instrument: 'front' },
  { name: '中村 樹', instrument: 'front' },
  { name: '清水 悠成', instrument: 'front' },
  { name: '林 陸', instrument: 'front' },
  { name: '中野 星那', instrument: 'front' },
  { name: '山田 陽', instrument: 'front' },
  { name: '渡辺 莉央', instrument: 'front' },
  { name: '森田 朝陽', instrument: 'front' },
  { name: '加藤 美優', instrument: 'vocal' },
  { name: '杉山 莉奈', instrument: 'vocal' },
  { name: '高橋 希空', instrument: 'vocal' },
];

export const songTitles = [
  'Autumn Leaves',
  'Blue Bossa',
  'All The Things You Are',
  'Stella By Starlight',
  'There Will Never Be Another You',
  'On Green Dolphin Street',
  'Take The A Train',
  'Misty',
  'Satin Doll',
  'My Funny Valentine',
  'Fly Me To The Moon',
  'Days Of Wine And Roses',
  'Solar',
  'Softly, As In A Morning Sunrise',
  'Just Friends',
  'There Is No Greater Love',
  'Someday My Prince Will Come',
  'How High The Moon',
  'Beautiful Love',
  'Night And Day',
];

export const vocalKeys = ['C', 'Eb', 'F', 'G', 'Bb', 'D'];